name: Update Sentrifugo
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Install on remote Server
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ SSH_HOST }}
        username: ${{ SSH_USER }}
        password: ${{ SSH_PASSWORD }}
        port: ${{ SSH_PORT }}
        script: |
          cd /var/www/html/
          git pull origin master